version: '3'

services:
  app:
    image: ghcr.io/yoganovvaindra/wedding-api-php:latest
    container_name: undangan-app
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - undangan
    environment:
      BASEURL: http://localhost:8080
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: wedding
      DB_USERNAME: root
      DB_PASSWORD: 
      TIMEZONE: Asia/Jakarta
      JWT_KEY: secret

#   db:
#     image: postgres:latest
#     container_name: undangan-db
#     environment:
#       POSTGRES_DB: undangan
#       POSTGRES_USER: root
#       POSTGRES_PASSWORD: 12345678
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     networks:
#       - undangan

  nginx:
    image: ghcr.io/yoganovvaindra/wedding-api-nginx:latest
    container_name: undangan-nginx
    ports:
      - 8080:80
    networks:
      - undangan
    depends_on:
      - app
    environment:
      BASEURL: http://localhost:8080
      DB_CONNECTION: mysql
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: wedding
      DB_USERNAME: root
      DB_PASSWORD: 
      TIMEZONE: Asia/Jakarta
      JWT_KEY: secret
    restart: unless-stopped

# volumes:
#   postgres_data:

networks:
  undangan:
    driver: bridge